site_name: Radar UnB

nav:
  - Início: index.md
  - Escopo: escopo/escopo.md
  - Problema: problema/problema.md
  - Requisitos:
    - Requisitos Funcionais: requisitos/req-funcionais.md
    - Requisitos Não-Funcionais: requisitos/req-nao-funcionais.md
  - Épicos:
    - Controle de Acesso: epicos/01-controle-de-acesso.md
    - Mapa Interativo: epicos/02-mapa-interativo.md
    - Gestão de Ocorrências: epicos/03-gestao-de-ocorrencias.md

theme:
  name: material
  features:
    - navigation.tabs
    - content.code.copy
    - content.action.edit
  custom_dir: overrides

markdown_extensions:
  - meta
  - pymdownx.superfences

extra:
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/thumb-up-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/thumb-down-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback!
